version: '3'


services:
  tomcat:
    build: ./tomcat
    image: lmtomcat:1.0.0
    container_name: lmtomcatcon
    restart: always
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:5005:5005
    networks:
      - lmnetwork
    environment:
      CATALINA_OPTS: "-Xdebug -Xrunjdwp:transport=dt_socket,address=5005,suspend=n,server=y"
    volumes:
      - /home/jelly-lemon/images:/images


  mysql:
    build: ./mysql
    image: lmmysql:1.0.0
    container_name: lmmysqlcon
    restart: always
    ports:
      - 0.0.0.0:3306:3306
    networks:
      lmnetwork: 
       aliases: 
         - mysql_service

    volumes:
      - /home/jelly-lemon/mysqldata:/var/lib/mysql
#      - /etc/timezone:/etc/timezone
#      - /etc/localtime:/etc/localtime


networks:
  lmnetwork:
    driver: bridge


      
#      ipam:
#        driver: default
#        config:
#          - subnet: 172.18.0.0/24
#            gateway: 172.18.0.1
  
    